### ISSUE TITLE
Make it more like SASS

### ISSUE THREAD

**Issue by hyuri** [beeware/colosseum#100]
### What is the problem or limitation you are having?

CSS has some limitations when it comes to modularity.

### Describe the solution you'd like

Add SASS features, so the code can be more modular.

### Describe alternatives you've considered

None

**Comment by freakboy3742** [comment]
I'm going to close this as out of scope for Colosseum.

Colosseum aims to be a CSS3 implementation. SASS is a very specific set of APIs for building CSS, but isn't literal CSS itself. 

There might be scope for a SASS-alike API that *wraps* Colosseum - but that doesn't mean the API needs to be in Colosseum.
