### ISSUE TITLE
Colosseum width-014.json reference file wrong?

### ISSUE THREAD

**Issue by canalreeds** [beeware/colosseum#27]
The Width-014 test for Colosseum creates a div of 1" height (which comes out to 96 px) by 1 px width, as seen here:

http://test.csswg.org/suites/css21_dev/nightly-unstable/html4/width-014.htm

The reference file for this test (colosseum/tests/web_platform/CSS2/normal_flow/ref/width-014.json) specifies it as 1.328125 px by 96 px.

This appears to be an incomplete reference file. The data file does return the correct value, but as the reference is incorrect, the test shows as failing.

...and in the event that I went about this all wrong and said something obvious or silly, do forgive me as I'm new and have no idea what I'm doing.

**Comment by freakboy3742** [comment]
This appears to have been addressed by #48.
