### ISSUE TITLE
Outdated Release Version of Colosseum on PyPi 

### ISSUE THREAD

**Issue by strawstack** [beeware/colosseum#33]
# Issue
The [tutorial](https://colosseum.readthedocs.io/en/latest/tutorial/tutorial-1.html) contains code that does not work on the current release of colosseum. 

# Steps to Reproduce 
1. Run `pip install colosseum`
2. Start Python interpreter
3. Run `from colosseum.dimensions import Size, Box`
4. Observe error message `ModuleNotFoundError: No module named 'colosseum.dimensions'`

The current release version of `colosseum` does not contains the `dimensions` module. See [release history](https://pypi.org/project/colosseum/#history).

# Related Screenshot
<img width="718" alt="Screen Shot 2019-05-06 at 11 15 32 AM" src="https://user-images.githubusercontent.com/3249652/57235785-a6568400-6ff1-11e9-9361-7c83be6e9072.png">

**Comment by freakboy3742** [comment]
I've just pushed a 0.2.0 release to PyPI - that should resolve this issue.
