### ISSUE TITLE
MyDOMNode Attribute is not Initialized 

### ISSUE THREAD

**Issue by strawstack** [beeware/colosseum#35]
# Issue

The following code, shown below, from [this tutorial](https://colosseum.readthedocs.io/en/latest/tutorial/tutorial-1.html) returns `<Box (0x0 @ 0,0)>` rather than what is expected: `<Box (1000x1000 @ 0,0)>`

# Steps to Reproduce

Run the following lines of code as outlined in [this tutorial](https://colosseum.readthedocs.io/en/latest/tutorial/tutorial-1.html):
````
>>> from colosseum import CSS
>>> node = MyDOMNode(style=CSS(width=1000, height=1000))
>>> layout = node.layout
>>> print(node.layout)
````
The response from `print(node.layout)` reveals that the `width` passed to the CSS object is not used by the resulting MyDOMNode object.

**Comment by strawstack** [comment]
The structure of `MyDomNode` as shown in the screenshot assigns `Box(self)` to layout:
![Screen Shot 2019-05-06 at 3 21 53 PM](https://user-images.githubusercontent.com/3249652/57249419-df532080-7012-11e9-93b2-335a8fbb76bb.png)

Inspecting the Box object reveals the `.content_width` attribute of the class is used in the `__repr__` method. However, the `content_width` attribute is only set by a line inside the `_reset` method: `self.content_width = 0`. 

The issue I can see is that the `content_width` property has no relation to the location where the `width` is actually stored, which is `MyDOMNode.style.width`

**Comment by peractio** [comment]
could we just add a `content_dims` optional argument to the `Box` constructor? and pass in a tuple to set `content_width` and `content_height`
