### ISSUE TITLE
Technical reference page is lists is empty

### ISSUE THREAD

**Issue by donno** [beeware/colosseum#85]
**Describe the bug**
The README points to the [Technical reference](http://colosseum.readthedocs.io/en/latest/reference/index.html) but it is is essentially empty. It states "This is the technical reference for public APIs provided by Colosseum.".

**To Reproduce**
1. Go to the [Technical reference](http://colosseum.readthedocs.io/en/latest/reference/index.html). 
2. See lack of content.

**Expected behavior**
A list of classes and functions.

**Screenshots**

**Environment:**
 - Software versions:
   - Browser: Firefox 9.3 (64-bit).

**Comment by freakboy3742** [comment]
Yes. We need to write a lot of documentation. The project is at v0.3, so there's a lot of things missing at this point. However, having individual tickets reporting this don't actually help us keep track of this problem.
